# Copyright 2020. All Rights Reserved.
# Author: fangjun.kuang@gmail.com (Fangjun Kuang)

workspace(name = "ruy_example")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "ruy",
    sha256 = "7303b7b0827e96f8a0417ed7ceb0d564552153947a999d24c470f63609427a2f",
    strip_prefix = "ruy-4452e73747d162f86aadc614f3296420d0d345a9",
    urls = [
        "https://github.com/google/ruy/archive/4452e73747d162f86aadc614f3296420d0d345a9.tar.gz",
    ],
)
