#include "extent.h"
#include "integral_constant.h"
#include "is_array.h"
#include "is_assignable.h"
#include "is_const.h"
#include "is_lvalue_reference.h"
#include "is_member_pointer.h"
#include "is_nullptr.h"
#include "is_pointer.h"
#include "is_reference.h"
#include "is_rvalue_reference.h"
#include "is_same.h"
#include "is_void.h"
#include "rank.h"
#include "remove_all_extents.h"
#include "remove_const.h"
#include "remove_cv.h"
#include "remove_extent.h"
#include "remove_reference.h"
#include "remove_volatile.h"
#include "void_t.h"

int main() { return 0; }
